// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;

import frc.robot.commands.JoystickControl;

import com.revrobotics.CANSparkMax;

import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;


/**
 *
 */
public class DriveTrain extends SubsystemBase {

    private DifferentialDrive differentialDrive;

    public DriveTrain() {

        differentialDrive = new DifferentialDrive(new CANSparkMax(2, MotorType.kBrushless),
                new CANSparkMax(4, MotorType.kBrushless));
        setDefaultCommand(new JoystickControl(this));

    }

    public void setSpeed(double speed) {
        differentialDrive.tankDrive(speed, speed); // Move
    }

    public void setTankSpeed(double speed1, double speed2) {
        differentialDrive.tankDrive(0.85 * speed1, 0.85 * speed2);
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    public void arcadeDrive(double xSpeed, double zRotation) {
        differentialDrive.arcadeDrive(xSpeed, zRotation);
        // System.out.println("Left encoder:"+ getEncoderLeft());
        // System.out.println("Right encoder:"+ getEncoderRight());
    }

}
