// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc9998.Droids2019.subsystems;


import org.usfirst.frc9998.Droids2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.Servo;

import java.awt.Color;
//import com.mach.LightDrive.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class LightDrive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// LightDriveSerial ldrive_serial;
    // LightDriveCAN ldrive_can;
//    LightDrivePWM ldrive_pwm;
	Servo servo1;
	Servo servo2;

    
    public LightDrive() {

		// ldrive_serial = new LightDriveSerial();
        // ldrive_serial.SetColor(1, new Color(0,255,0), 1.0);
        // ldrive_serial.Update();

        // ldrive_can = new LightDriveCAN();
        // ldrive_can.SetColor(1, new Color(0,255,0), 1.0);
        // ldrive_can.Update();

        //Initialize 2 Servo outputs for a PWM LightDrive
		servo1 = new Servo(0);
		servo2 = new Servo(1);
		//Initialize a new PWM LightDrive
      /*  ldrive_pwm = new LightDrivePWM(servo1, servo2);
        ldrive_pwm.SetColor(1, new Color(0,255,0));
        ldrive_pwm.SetLevel(1, 255);
        ldrive_pwm.Update();
*/

        // ldrive_can.SetColor(1, Color.BLUE, (float) 0.8);
		// ldrive_can.SetColor(2, Color.GREEN, (float) 0.8);
		// ldrive_can.SetColor(3, Color.RED, (float) 0.8);
        // ldrive_can.SetColor(4, Color.YELLOW, (float) 0.8);
        
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    public void onGreenLight() {
        // ldrive_serial.SetColor(1, new Color(0,255,0), 1.0);
        // ldrive_serial.Update();
/*
        ldrive_pwm.SetColor(1, new Color(0,255,0));
        ldrive_pwm.SetLevel(1, 255);
        ldrive_pwm.Update();
*/
        // ldrive_can.SetColor(1, new Color(0,255,0), 1.0);
        // ldrive_can.Update();
    }

    public void offGreenLight() {
        // ldrive_serial.SetColor(1, new Color(0,0,0), 0.0);
        // ldrive_serial.Update();

        // Use the following:
/*        ldrive_pwm.SetColor(1, new Color(0,0,0));
        ldrive_pwm.SetLevel(1, 0);
        ldrive_pwm.Update();
        // End here
*/
        // ldrive_pwm.SetColor(1, new Color(0,255,0));
        // ldrive_pwm.SetLevel(1, 255);
        // ldrive_pwm.Update();

        // ldrive_can.SetColor(1, new Color(0,0,0), 0.0);
        // ldrive_can.Update();
    }

    public float getVoltage() {
        // return(ldrive_serial.GetVoltage());
        return (float) (1.0);
        // return(ldrive_can.GetVoltage());
    }
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

